application: message-downloader
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# taskqueue
- url: /parse
  script: worker.app
  login: admin

# normal request
- url: /static
  static_dir: static
- url: /.*
  script: messagedownloader.app
  secure: optional
  login: required

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest
